import type { NextPage } from 'next';
import { useEffect, useState } from 'react';
import Head from 'next/head';
import { Button } from '@mui/material';

import { connect, sendMessage, SocketData } from '../modules/Home/api/socket';
import Header from '../modules/Home/components/Header';
import ChatHistory from '../modules/Home/components/ChatHistory';
import ChatInput from '../modules/Home/components/ChatInput';

const Home: NextPage = () => {
  const [chatHistory, setChatHistory] = useState<SocketData[]>([]);
  const [inputChat, setInputChat] = useState('Hello world');

  console.log('input chat state:', inputChat);

  useEffect(() => {
    connect((data) => {
      setChatHistory((prev) => [...prev, data]);
    });
  }, []);

  const handleSend = () => {
    sendMessage({ message: inputChat });
    setInputChat('');
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <ChatHistory chatHistory={chatHistory} />
        <ChatInput
          value={inputChat}
          onChange={(e) => setInputChat(e.target.value)}
        />
        <Button variant="contained" onClick={handleSend}>
          Send Message
        </Button>
      </main>
    </div>
  );
};

export default Home;
